import {beforeAll,afterAll,describe,it,expect} from 'vitest';
import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
const alice='11111111-1111-4111-8111-111111111111',bob='22222222-2222-4222-8222-222222222222',charlie='33333333-3333-4333-8333-333333333333';
let db:PGlite;let session:string;let group:string;let code:string;
async function user(id:string){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');}
async function admin(){await db.exec('reset role');}
async function rpc(name:string,args:unknown[]=[]){const result=await db.query<{value:any}>(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) as value`,args);return result.rows[0].value;}
beforeAll(async()=>{
 db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
 create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}',created_at timestamptz default now());
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth,public,storage to authenticated,anon;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;
 grant all on storage.objects to authenticated;
 `);
 await db.exec(await readFile(new URL('../supabase/migrations/001_pushup.sql',import.meta.url),'utf8'));
 for(const [id,name]of [[alice,'Alice'],[bob,'Bob'],[charlie,'Charlie']])await db.query('insert into auth.users(id,raw_user_meta_data) values($1,$2)',[id,JSON.stringify({nickname:name})]);
 await db.query("insert into workouts(id,user_id,started_at,ended_at) values('99999999-9999-4999-8999-999999999999',$1,now()-interval '2 hours',now()-interval '1 hour')",[alice]);
 await db.exec(await readFile(new URL('../supabase/migrations/002_exercise_modes.sql',import.meta.url),'utf8'));
 await user(alice);
});
afterAll(async()=>{await db?.close();});
describe.sequential('database RPCs and access control',()=>{
 it('creates profile and limits each account to one active session',async()=>{const a=await rpc('start_workout'),b=await rpc('start_workout');session=a.id;expect(a.id).toBe(b.id);expect((await rpc('app_snapshot')).profile.nickname).toBe('Alice');await admin();await db.query("update workouts set started_at=now()-interval '1 minute' where id=$1",[session]);await user(alice);});
 it('accepts ordered reps and makes retries idempotent',async()=>{const batch=JSON.stringify([{seq:1,elapsed_ms:1000},{seq:2,elapsed_ms:2000}]);expect(await rpc('submit_reps',[session,batch])).toBe(2);expect(await rpc('submit_reps',[session,batch])).toBe(2);expect((await rpc('app_snapshot')).total).toBe(2);});
 it('rejects changed retries, gaps, implausible speed and future times',async()=>{for(const event of [{seq:1,elapsed_ms:1500},{seq:4,elapsed_ms:4000},{seq:3,elapsed_ms:2100},{seq:3,elapsed_ms:120000}])await expect(rpc('submit_reps',[session,JSON.stringify([event])])).rejects.toThrow();});
 it('denies direct counter writes and another user’s session',async()=>{await expect(db.query('insert into rep_events values($1,3,3000,now())',[session])).rejects.toThrow();await user(bob);expect((await db.query('select * from workouts')).rows).toHaveLength(0);await expect(rpc('submit_reps',[session,'[]'])).rejects.toThrow();await expect(rpc('finish_workout',[session,0])).rejects.toThrow();await user(alice);});
 it('creates private groups and rejects non-member ranking access',async()=>{group=await rpc('create_group',['Test Crew']);code=(await rpc('app_snapshot')).groups[0].invite_code;await user(bob);expect((await rpc('app_snapshot')).groups).toHaveLength(0);await expect(rpc('leaderboard',['2026-09-20',group])).rejects.toThrow();});
 it('joins idempotently and keeps invite codes private',async()=>{expect((await rpc('join_group',[code])).id).toBe(group);await rpc('join_group',[code]);const snapshot=await rpc('app_snapshot');expect(snapshot.groups[0].member_count).toBe(2);await expect(db.query('select invite_code from groups')).rejects.toThrow();});
 it('prevents non-owner group administration',async()=>{await expect(rpc('manage_group',[group,'rotate',null])).rejects.toThrow();await expect(rpc('manage_group',[group,'remove',alice])).rejects.toThrow();});
 it('rate limits invalid invite attempts without rolling back counters',async()=>{await user(charlie);for(let i=0;i<10;i++)expect((await rpc('join_group',['WRONG'])).error).toContain('not found');expect((await rpc('join_group',[code])).error).toContain('Too many');await user(alice);});
 it('does not backfill repetitions completed before joining a group',async()=>{const day=(await db.query<{day:string}>("select (now() at time zone 'Asia/Kuala_Lumpur')::date::text as day")).rows[0].day;const rows=await rpc('leaderboard',[day,group]);expect(rows.find((r:any)=>r.user_id===alice).count).toBe(0);});
 it('finishing is idempotent and prevents new reps',async()=>{const first=await rpc('finish_workout',[session,3]);const second=await rpc('finish_workout',[session,10]);expect(second.ended_at).toBe(first.ended_at);expect(second.rejected).toBe(3);await expect(rpc('submit_reps',[session,JSON.stringify([{seq:3,elapsed_ms:3000}])])).rejects.toThrow();});
 it('ties share a rank and midnight events are allocated by completion date',async()=>{await admin();await db.query("insert into workouts(id,user_id,started_at,ended_at) values('44444444-4444-4444-8444-444444444444',$1,'2026-09-20T15:59:58Z','2026-09-20T16:01:00Z')",[alice]);await db.exec("insert into rep_events values('44444444-4444-4444-8444-444444444444',1,1000,'2026-09-20T15:59:59Z'),('44444444-4444-4444-8444-444444444444',2,2000,'2026-09-20T16:00:00Z')");await user(alice);const before=await rpc('activity_on_date',['2026-09-20']),after=await rpc('activity_on_date',['2026-09-21']);expect(before.find((w:any)=>w.id==='44444444-4444-4444-8444-444444444444').accepted).toBe(1);expect(after.find((w:any)=>w.id==='44444444-4444-4444-8444-444444444444').accepted).toBe(1);const empty=await rpc('leaderboard',['2020-01-01',null]);expect(empty.every((r:any)=>r.rank===1)).toBe(true);expect(Object.keys(empty[0]).sort()).toEqual(['avatar_url','count','nickname','rank','user_id'].sort());});
 it('rotated codes stop working and leaving retains personal history',async()=>{await rpc('manage_group',[group,'rotate',null]);await user(bob);await rpc('manage_group',[group,'leave',null]);expect((await rpc('join_group',[code])).error).toContain('not found');await user(alice);const before=(await rpc('app_snapshot')).total;await rpc('manage_group',[group,'delete',null]);expect((await rpc('app_snapshot')).total).toBe(before);});
 it('restricts avatar writes to the account path',async()=>{await expect(db.query("insert into storage.objects(bucket_id,name) values('avatars',$1)",[bob+'/avatar.webp'])).rejects.toThrow();await db.query("insert into storage.objects(bucket_id,name) values('avatars',$1)",[alice+'/avatar.webp']);});
});

describe.sequential('mode migration and server-owned scores',()=>{
 it('backfills legacy workouts as standard and ranked',async()=>{await user(alice);const w=(await rpc('app_snapshot')).workouts.find((w:any)=>w.id==='99999999-9999-4999-8999-999999999999');expect(w.mode).toBe('standard');expect(w.ranked).toBe(true);});
 it('locks mode on active sessions and leaves old standard clients compatible',async()=>{const w=await rpc('start_workout',['knee']);expect(w.mode).toBe('knee');expect(w.ranked).toBe(false);expect((await rpc('start_workout',['knee'])).id).toBe(w.id);expect((await rpc('app_snapshot')).active.mode).toBe('knee');await expect(rpc('start_workout',['crunch'])).rejects.toThrow(/Finish/);await expect(rpc('start_workout')).rejects.toThrow(/Finish/);await expect(db.query("update workouts set mode='standard' where id=$1",[w.id])).rejects.toThrow();await rpc('finish_workout',[w.id,0]);});
 it('rejects unknown modes and client eligibility changes',async()=>{await expect(rpc('start_workout',['squat'])).rejects.toThrow(/Unknown/);await expect(db.exec("update exercise_configs set ranked_enabled=true")).rejects.toThrow();});
 it('adds each event to only its session mode; retry cannot inflate it',async()=>{for(const mode of ['standard','knee','crunch','situp']){const before=await rpc('app_snapshot');const w=await rpc('start_workout',[mode]);const batch=JSON.stringify([{seq:1,elapsed_ms:1000}]);await rpc('submit_reps',[w.id,batch]);await rpc('submit_reps',[w.id,batch]);const after=await rpc('app_snapshot');for(const m of ['standard','knee','crunch','situp'])expect(after.totalsByMode[m]).toBe(before.totalsByMode[m]+(m===mode?1:0));expect(after.total).toBe(after.totalsByMode.standard);expect(after.workouts.find((x:any)=>x.id===w.id).mode).toBe(mode);await rpc('finish_workout',[w.id,1]);}});
 it('keeps practice out of all leaderboards and does not retroactively promote it',async()=>{const day=(await db.query<{day:string}>("select (now() at time zone 'Asia/Kuala_Lumpur')::date::text as day")).rows[0].day;expect((await rpc('leaderboard',[day,null,'knee'])).every((r:any)=>r.count===0)).toBe(true);await admin();await db.exec("update exercise_configs set ranked_enabled=true where mode='knee'");await user(alice);expect((await rpc('leaderboard',[day,null,'knee'])).every((r:any)=>r.count===0)).toBe(true);const w=await rpc('start_workout',['knee']);expect(w.ranked).toBe(true);await rpc('submit_reps',[w.id,JSON.stringify([{seq:1,elapsed_ms:1000}])]);await rpc('finish_workout',[w.id,0]);expect((await rpc('leaderboard',[day,null,'knee'])).find((r:any)=>r.user_id===alice).count).toBe(1);});
 it('filters dates across midnight and all-mode history without mixing totals',async()=>{await admin();await db.query("insert into workouts(id,user_id,mode,ranked,started_at,ended_at) values('88888888-8888-4888-8888-888888888888',$1,'crunch',false,'2026-09-19T15:59:58Z','2026-09-19T16:01:00Z')",[alice]);await db.exec("insert into rep_events values('88888888-8888-4888-8888-888888888888',1,1000,'2026-09-19T15:59:59Z'),('88888888-8888-4888-8888-888888888888',2,2000,'2026-09-19T16:00:00Z')");await user(alice);for(const day of ['2026-09-19','2026-09-20']){const crunch=await rpc('activity_on_date',[day,'crunch']);expect(crunch.find((w:any)=>w.id==='88888888-8888-4888-8888-888888888888').accepted).toBe(1);expect((await rpc('activity_on_date',[day,'standard'])).every((w:any)=>w.mode==='standard')).toBe(true);expect((await rpc('activity_on_date',[day,'all'])).some((w:any)=>w.mode==='crunch')).toBe(true);}await user(bob);expect((await rpc('app_snapshot')).totalsByMode.crunch).toBe(0);await user(alice);});
 it('protects immutable mode even through privileged accidental updates',async()=>{await admin();await expect(db.exec("update workouts set mode='situp' where id='88888888-8888-4888-8888-888888888888'")).rejects.toThrow(/immutable/);await user(alice);});
});
