'use client';
import { useEffect, useRef, useState } from 'react';
import { X, ZoomIn } from 'lucide-react';
import { ModalFrame } from './modal-frame';
export function AvatarCrop({file,busy,onSave,onCancel}:{file:File;busy:boolean;onSave:(blob:Blob)=>void;onCancel:()=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),img=useRef<HTMLImageElement|null>(null);const [zoom,setZoom]=useState(1),[x,setX]=useState(50),[y,setY]=useState(50),[ready,setReady]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let live=true;const url=URL.createObjectURL(file),image=new Image();image.onload=()=>{if(live){img.current=image;setReady(true);}};image.onerror=()=>setError('This image could not be opened. Try a JPG or PNG.');image.src=url;return()=>{live=false;URL.revokeObjectURL(url);};},[file]);
 useEffect(()=>{if(!ready||!canvas.current||!img.current)return;const image=img.current,ctx=canvas.current.getContext('2d')!;const side=Math.min(image.naturalWidth,image.naturalHeight)/zoom;ctx.clearRect(0,0,512,512);ctx.drawImage(image,(image.naturalWidth-side)*x/100,(image.naturalHeight-side)*y/100,side,side,0,0,512,512);},[ready,zoom,x,y]);
 return <ModalFrame onClose={onCancel}><section className="modal crop-modal" role="dialog" aria-modal="true" aria-labelledby="crop-title"><button className="icon-button modal-close" aria-label="Cancel crop" onClick={onCancel}><X size={20}/></button><h2 id="crop-title">Your best angle.</h2><p>Adjust your photo to fit the circle.</p>{error?<p role="alert">{error}</p>:<><canvas className="crop-canvas" width={512} height={512} ref={canvas}/><label><ZoomIn size={16}/> Zoom<input type="range" min="1" max="3" step="0.05" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><label>Horizontal position<input type="range" min="0" max="100" value={x} onChange={e=>setX(Number(e.target.value))}/></label><label>Vertical position<input type="range" min="0" max="100" value={y} onChange={e=>setY(Number(e.target.value))}/></label><button className="button primary full-width" disabled={!ready||busy} onClick={()=>canvas.current?.toBlob(blob=>{if(blob)onSave(blob);else setError('Unable to process this photo.');},'image/webp',.85)}>{busy?'Saving photo…':'Use this photo'}</button></>}</section></ModalFrame>;
}
