'use client';
import Link from 'next/link';
import { MODES, EXERCISE_MODES, modeOf } from '@/lib/modes';
import { ModePicker } from './mode-picker';
import { useEffect, useMemo, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Copy, Dumbbell, Flame, Globe2, ImagePlus, LogOut, Medal, MoreHorizontal, Plus, RefreshCw, ShieldCheck, Target, Trophy, Users, X } from 'lucide-react';
import { useApp } from './shell';
import { AthleteArt, Avatar, Empty, SectionHeading, TextLink } from './ui';
import { api } from '@/lib/api';
import { demoRankings } from '@/lib/demo';
import { dateShift, dayKey, displayDate, duration } from '@/lib/time';
import type { Group, Ranking, Workout } from '@/lib/types';
import { browserClient } from '@/lib/supabase/client';
import { AvatarCrop } from './avatar-crop';
import { ModalFrame } from './modal-frame';

function useRankings(day:string,group:string|null=null){
 const {demo,notice,mode}=useApp();const [rows,setRows]=useState<Ranking[]>(demo?demoRankings(mode):[]),[loading,setLoading]=useState(!demo);
 useEffect(()=>{let live=true;setLoading(true);if(demo){setRows(demoRankings(mode));setLoading(false);return;}
 const load=()=>api<Ranking[]>('leaderboard',{day,group,mode}).then(r=>{if(live){setRows(r);setLoading(false);}}).catch(e=>{if(live){notice(e.message);setLoading(false);}});
 void load();const interval=setInterval(load,30000);return()=>{live=false;clearInterval(interval);};},[day,group,demo,notice,mode]);
 return {rows,loading};
}
function useToday(){const [today,setToday]=useState(dayKey());useEffect(()=>{const t=setInterval(()=>setToday(dayKey()),10000);return()=>clearInterval(t);},[]);return today;}
function Title({eyebrow,title,subtitle,children}:{eyebrow?:string;title:string;subtitle:string;children?:React.ReactNode}){return <div className="page-title"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1><p>{subtitle}</p></div>{children}</div>;}
function WorkoutRows({rows,dateScoped=false}:{rows:Workout[];dateScoped?:boolean}){return rows.length?<div className="workout-list">{rows.map(w=><div className="workout-row" key={w.id}><span className="workout-icon"><Dumbbell size={21}/></span><div className="workout-name"><strong>{new Date(w.started_at).toLocaleTimeString('en-GB',{timeZone:'Asia/Kuala_Lumpur',hour:'2-digit',minute:'2-digit'})} · {MODES[modeOf(w.mode)].label}</strong><span>{displayDate(w.started_at,{year:'numeric'})} <i/> {duration(w.duration_seconds)} <i/> {w.rejected} rejected {w.ended_at?'':' · In progress'}</span></div><div className="workout-count"><strong>{w.accepted}</strong><span>{dateScoped?'reps on this date':'reps'}</span></div><span className="verified-tag"><ShieldCheck size={13}/> {w.ranked===false?'Practice':'Counted'}</span></div>)}</div>:<Empty title="A fresh start">Your completed workouts will appear here. Every rep is a little progress.</Empty>;}
function RankingRows({rows,compact=false}:{rows:Ranking[];compact?:boolean}){const {data}=useApp();return <div className={`ranking-list ${compact?'compact':''}`}>{rows.map(r=><div key={r.user_id} className={`ranking-row ${r.user_id===data.profile.id?'you':''}`}><span className={`rank rank-${r.rank}`}>{r.rank<=3?<Medal size={20}/>:String(r.rank).padStart(2,'0')}</span><Avatar name={r.nickname} src={r.avatar_url} size="small"/><div className="ranking-name">{r.nickname}{r.user_id===data.profile.id&&<span className="you-label">You</span>}</div><strong>{r.count.toLocaleString()}<small> reps</small></strong></div>)}</div>;}
export function Dashboard(){
 const {data,mode}=useApp(),today=useToday();const {rows}=useRankings(today);const [range,setRange]=useState(7);
 const totalToday=data.daily.find(d=>d.day===today)?.count??0;const myRank=rows.find(r=>r.user_id===data.profile.id);
 const days=Array.from({length:range},(_,i)=>dateShift(today,i-range+1));const counts=days.map(day=>data.daily.find(d=>d.day===day)?.count??0);const max=Math.max(20,...counts);
 let streak=0;for(let i=(totalToday?0:1);i<3660;i++){if(!(data.daily.find(d=>d.day===dateShift(today,-i))?.count))break;streak++;}
 const weekTotal=counts.reduce((a,b)=>a+b,0);
 return <>
  <Title eyebrow={displayDate(new Date(),{weekday:'long',year:'numeric'}).toUpperCase()} title={`Let’s make it count, ${data.profile.nickname.split(' ')[0]}.`} subtitle="A little progress today. A stronger you tomorrow."><Link href="/workout" className="button primary"><Plus size={19}/>Start workout</Link></Title>
  <div className="dashboard-top"><section className="hero-card"><div className="hero-copy"><span className="pill"><span className="orange-dot"/> YOUR ONLY COMPETITION IS YESTERDAY</span><h2>Show up.<br/>Push yourself.</h2><p>No shortcuts. Just you, your effort,<br className="desktop-break"/> and one good rep at a time.</p><Link href="/workout" className="button dark">Start {MODES[mode].label.toLowerCase()} <ArrowUpRight size={17}/></Link><span className="hero-footnote"><ShieldCheck size={13}/>Camera-counted. Always private.</span></div><AthleteArt/><div className="art-badge"><span className="badge-check"><Check size={15}/></span><div><strong>Good form. Great progress.</strong><span>Make every rep mean something.</span></div></div></section><section className="today-card"><div className="card-topline"><span>TODAY’S EFFORT</span><span className="mini-icon"><Dumbbell size={18}/></span></div><div className="today-number">{totalToday}<span>{MODES[mode].label.toLowerCase()} reps</span></div><div className="effort-divider"/><div className="today-stat"><span><Trophy size={16}/> Global position</span><strong>{myRank&&myRank.count?`#${myRank.rank}`:'—'}</strong></div><div className="today-stat"><span><Clock3 size={16}/> Next reset</span><strong>00:00 MYT</strong></div><Link className="today-link" href="/competition">See where you stand <ArrowRight size={15}/></Link></section></div>
  <div className="stats-grid"><div className="stat-card"><span className="stat-icon orange"><Dumbbell size={21}/></span><div><span>Lifetime {MODES[mode].label.toLowerCase()} reps</span><strong>{data.total.toLocaleString()}<small>reps</small></strong></div><span className="stat-note">Every one earned</span></div><div className="stat-card"><span className="stat-icon yellow"><Flame size={22}/></span><div><span>Current streak</span><strong>{streak}<small>{streak===1?'day':'days'}</small></strong></div><span className="stat-note">Keep showing up</span></div><div className="stat-card"><span className="stat-icon purple"><Users size={21}/></span><div><span>Your community</span><strong>{data.groups.length}<small>{data.groups.length===1?'group':'groups'}</small></strong></div><Link className="stat-arrow" href="/groups" aria-label="View groups"><ArrowUpRight size={21}/></Link></div></div>
  <div className="dashboard-middle"><section className="card progress-card"><SectionHeading title="Consistency looks good on you" caption={`Your daily ${MODES[mode].label.toLowerCase()} reps.`}><div className="segmented"><button className={range===7?'selected':''} onClick={()=>setRange(7)}>Week</button><button className={range===28?'selected':''} onClick={()=>setRange(28)}>Month</button></div></SectionHeading><div className="chart-summary"><strong>{weekTotal.toLocaleString()}</strong><span>reps this {range===7?'week':'month'}</span><span className="chart-key"><span className="orange-dot"/>Accepted reps</span></div><div className="bar-chart" role="img" aria-label={`${range} days of ${MODES[mode].label}: ${days.map((d,i)=>`${d}: ${counts[i]}`).join(', ')}`}><div className="chart-grid"><span>{max}</span><span>{Math.round(max/2)}</span><span>0</span></div><div className="bars">{days.map((day,i)=><div className={`bar-column ${day===today?'current':''}`} key={day}><div className="bar-track"><div className="bar" style={{height:`${counts[i]/max*100}%`}} title={`${day}: ${counts[i]} reps`}>{range===7&&counts[i]>0&&<span>{counts[i]}</span>}</div></div><span>{range===7?displayDate(day+'T12:00:00+08:00',{weekday:'short',day:undefined,month:undefined}):i%4===0?day.slice(8):''}</span></div>)}</div></div><div className="chart-footer"><span><span className="green-dot"/>{counts.filter(Boolean).length} active days</span><span>{displayDate(days[0]+'T12:00:00+08:00')} – {displayDate(today+'T12:00:00+08:00')}</span></div></section><section className="card leaderboard-card"><SectionHeading title="A little friendly competition" caption="Today’s global leaderboard"><span className="outlined-icon"><Globe2 size={19}/></span></SectionHeading><RankingRows rows={rows.slice(0,4)} compact/><div className="leaderboard-bottom"><span>Stronger, together.</span><TextLink href="/competition">View leaderboard</TextLink></div></section></div>
  <section className="card"><SectionHeading title="The work you put in" caption="Your latest sessions, all in one place."><TextLink href="/activity">All activity</TextLink></SectionHeading><WorkoutRows rows={data.workouts.slice(0,3)}/></section>
 </>;
}
export function Activity(){
 const {data,demo,notice,mode,allData}=useApp();const [all,setAll]=useState(false);const today=useToday();const [selected,setSelected]=useState(today),[month,setMonth]=useState(today.slice(0,7)),[sessions,setSessions]=useState<Workout[]>([]),[loading,setLoading]=useState(false);
 useEffect(()=>{let live=true;if(demo){setSessions((all?allData.workouts:data.workouts).filter(w=>dayKey(w.started_at)===selected));return;}setLoading(true);api<Workout[]>('activity',{day:selected,mode:all?'all':mode}).then(r=>{if(live)setSessions(r);}).catch(e=>notice(e.message)).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[selected,demo,data.workouts,notice,mode,all,allData.workouts]);
 const first=`${month}-01`;const start=(new Date(first+'T12:00:00+08:00').getUTCDay()+6)%7;const daysInMonth=new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate();
 const move=(n:number)=>{const d=new Date(first+'T12:00:00+08:00');d.setUTCMonth(d.getUTCMonth()+n);setMonth(dayKey(d).slice(0,7));};
 const monthly=data.daily.filter(d=>d.day.startsWith(month));const sum=monthly.reduce((a,b)=>a+b.count,0);
 return <><Title eyebrow="YOUR PERSONAL RECORD" title="Small efforts. Real progress." subtitle="A record of every day you showed up."><Link className="button primary" href="/workout"><Plus size={18}/>Start workout</Link></Title><label className="history-scope"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>Show sessions from all four modes</label>{all&&<div className="mode-totals">{EXERCISE_MODES.map(m=><div key={m}><span>{MODES[m].label} · {selected}</span><strong>{allData.dailyByMode?.find(d=>d.day===selected&&d.mode===m)?.count??(m==='standard'?allData.daily.find(d=>d.day===selected)?.count??0:0)}</strong></div>)}</div>}<div className="activity-layout"><section className="card calendar-card"><div className="calendar-heading"><h2>{displayDate(first+'T12:00:00+08:00',{month:'long',year:'numeric',day:undefined})}</h2><div><button className="icon-button" onClick={()=>move(-1)} aria-label="Previous month"><ChevronLeft size={19}/></button><button className="icon-button" onClick={()=>move(1)} aria-label="Next month"><ChevronRight size={19}/></button></div></div><div className="calendar-grid">{['M','T','W','T','F','S','S'].map((d,i)=><span key={`h${i}`} className="calendar-weekday">{d}</span>)}{Array.from({length:start},(_,i)=><span key={`e${i}`}/>)}{Array.from({length:daysInMonth},(_,i)=>{const day=`${month}-${String(i+1).padStart(2,'0')}`,count=data.daily.find(d=>d.day===day)?.count??0;return <button key={day} aria-label={`${day}: ${count} ${mode==='standard'?'push-ups':MODES[mode].label+' reps'}`} aria-pressed={selected===day} onClick={()=>setSelected(day)} className={`calendar-day ${count?'has-activity':''} ${day===selected?'selected':''} ${day===today?'today':''}`}><span>{i+1}</span><small>{count||'·'}</small></button>;})}</div><div className="calendar-legend"><span className="orange-dot"/>A day you showed up <button className="text-button" onClick={()=>{setMonth(today.slice(0,7));setSelected(today);}}>Today</button></div></section><section className="month-story"><span className="mini-icon"><CalendarDays size={24}/></span><div className="eyebrow">YOUR MONTH IN MOTION</div><strong>{sum.toLocaleString()}</strong><p>{MODES[mode].label} reps. Each one a little stronger.</p><div className="month-facts"><div><b>{monthly.filter(d=>d.count>0).length}</b><span>active days</span></div><div><b>{Math.max(0,...monthly.map(d=>d.count))}</b><span>best day</span></div></div></section></div><section className="card"><SectionHeading title={displayDate(selected+'T12:00:00+08:00',{weekday:'long',year:'numeric'})} caption={`${data.daily.find(d=>d.day===selected)?.count??0} accepted ${MODES[mode].label.toLowerCase()} reps · Malaysia time`}/>{loading?<p className="loading">Loading your sessions…</p>:<WorkoutRows rows={sessions} dateScoped/>}</section><p className="fine-print">For sessions spanning midnight, repetitions appear on the day they were completed. Duration and rejected attempts describe the whole session.</p></>;
}
export function Competition(){
 const {data,mode,demo}=useApp();const today=useToday();const [date,setDate]=useState(today),[group,setGroup]=useState('');const {rows,loading}=useRankings(date,group||null);const mine=rows.find(r=>r.user_id===data.profile.id);
 return <><Title eyebrow="STRONGER TOGETHER" title="A little competition. A lot of progress." subtitle="Put in the reps. Find your people. Keep each other going."/>{MODES[mode].experimental&&<div className="mode-status">{MODES[mode].label} counting is experimental. Practice repetitions do not enter live rankings.{demo?' These standings are labelled sample data.':' Ranking opens only after reference validation.'}</div>}<div className="competition-toolbar"><div className="segmented"><button className={!group?'selected':''} onClick={()=>setGroup('')}><Globe2 size={16}/>Global</button><select aria-label="Group leaderboard" value={group} onChange={e=>setGroup(e.target.value)}><option value="">Your groups</option>{data.groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></div><label className="date-input"><CalendarDays size={17}/><input type="date" value={date} max={today} onChange={e=>{if(e.target.value)setDate(e.target.value);}} aria-label="Leaderboard date"/></label></div><div className="competition-summary"><div><span className="stat-icon orange"><Trophy size={24}/></span><div><span>Your position</span><strong>{mine&&mine.count?`#${mine.rank}`:'Unranked'}</strong></div></div><div><span>Your daily effort</span><strong>{mine?.count??0}<small> reps</small></strong></div><p><ShieldCheck size={19}/>Only camera-counted reps.<br/>One shared day. An honest effort.</p></div><section className="card full-leaderboard"><SectionHeading title={group?data.groups.find(g=>g.id===group)?.name??'Group leaderboard':'The daily leaderboard'} caption={`${displayDate(date+'T12:00:00+08:00',{year:'numeric'})} · Resets at 00:00 Malaysia time`}><span className="live-chip"><span className="green-dot"/>Daily standings</span></SectionHeading><div className="table-labels"><span>RANK</span><span>ATHLETE</span><span>REPS</span></div>{loading?<p className="loading">Finding your place…</p>:rows.length?<RankingRows rows={rows}/>:<Empty title="Be the first to show up">Start a workout and put the first repetitions on the board.</Empty>}<div className="leaderboard-rules">Equal counts share a rank. Showing the top 100 ranks and your position. {group?'Group scores count only reps completed after joining.':'Your personal session details stay private.'}</div></section></>;
}
export function Groups(){
 const {data,demo,setData,refresh,notice,mode,setMode}=useApp();const [modal,setModal]=useState<'create'|'join'|null>(null),[value,setValue]=useState(''),[busy,setBusy]=useState(false),[active,setActive]=useState<Group|null>(null);const {rows}=useRankings(dayKey(),active?.id??null);const [members,setMembers]=useState<Pick<Ranking,'user_id'|'nickname'|'avatar_url'>[]>([]);
 useEffect(()=>{let live=true;if(!active){setMembers([]);return;}if(demo){setMembers(demoRankings().slice(0,active.member_count));return;}api<Pick<Ranking,'user_id'|'nickname'|'avatar_url'>[]>('members',{group:active.id}).then(r=>{if(live)setMembers(r);}).catch(e=>notice(e.message));return()=>{live=false;};},[active,demo,notice,data.groups]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{if(demo){if(modal==='join')throw new Error('Invite codes connect real accounts after Supabase setup. Create a sample group to explore the interface.');const group={id:crypto.randomUUID(),name:value.trim(),owner_id:data.profile.id,invite_code:crypto.randomUUID().slice(0,8).toUpperCase(),member_count:1,joined_at:new Date().toISOString()};setData(d=>({...d,groups:[...d.groups,group]}));}else{await api(modal==='create'?'createGroup':'joinGroup',modal==='create'?{name:value}:{code:value});await refresh();}setModal(null);setValue('');notice(demo?'Sample group created for this preview.':modal==='create'?'Your group is ready. Share the invite code!':'You’re in. Welcome to the group!');}catch(e){notice((e as Error).message);}finally{setBusy(false);}};
 const manage=async(g:Group,operation:string,member?:string)=>{if(['delete','leave','remove'].includes(operation)&&!window.confirm(operation==='delete'?`Delete ${g.name}? Personal workout history will be kept.`:operation==='leave'?`Leave ${g.name}?`:'Remove this member from the group?'))return;setBusy(true);try{if(demo){if(operation==='rotate'){const code=crypto.randomUUID().slice(0,10).toUpperCase();setData(d=>({...d,groups:d.groups.map(x=>x.id===g.id?{...x,invite_code:code}:x)}));setActive({...g,invite_code:code});}else if(operation==='remove'){notice('Member removal requires connected accounts.');return;}else{setData(d=>({...d,groups:d.groups.filter(x=>x.id!==g.id)}));setActive(null);}}else{await api('manageGroup',{group:g.id,operation,member});await refresh();if(operation!=='remove')setActive(null);}notice('Group updated.');}catch(e){notice((e as Error).message);}finally{setBusy(false);}};
 const copy=async(code:string)=>{try{await navigator.clipboard.writeText(code);notice('Invite code copied. Send it to your friends.');}catch{notice(`Invite code: ${code}`);}};
 return <><Title eyebrow="FIND YOUR PEOPLE" title="Better with a little backup." subtitle="Your friends. Your daily leaderboard. Your reason to show up."><div className="button-row"><button className="button secondary" onClick={()=>{setValue('');setModal('join');}}>Join with a code</button><button className="button primary" onClick={()=>{setValue('');setModal('create');}}><Plus size={18}/>Create group</button></div></Title><div className="group-grid">{data.groups.map((g,i)=><section key={g.id} className="card group-card"><div className={`group-emblem emblem-${i%3}`}><Users size={27}/></div><span className="group-role">{g.owner_id===data.profile.id?'Created by you':'Member'}</span><h2>{g.name}</h2><p>{g.member_count} athletes showing up together</p><div className="group-avatars">{['Alex Lee','Jamie Chen','Maya Tan','Sam Kim'].slice(0,Math.min(g.member_count,4)).map((n,j)=><Avatar key={n} name={demo?n:(j===0?data.profile.nickname:'Athlete')} size="small"/>)}<span>{g.member_count>4?`+${g.member_count-4}`:'Let’s grow together'}</span></div><div className="invite-box"><span><small>INVITE CODE</small><strong>{g.invite_code}</strong></span><button className="icon-button" onClick={()=>copy(g.invite_code)} aria-label={`Copy invite code for ${g.name}`}><Copy size={17}/></button></div><button className="group-open" onClick={()=>setActive(g)}>Open group <ArrowUpRight size={17}/></button></section>)}<button className="new-group-card" onClick={()=>{setValue('');setModal('create');}}><span><Plus size={26}/></span><h3>Your next crew starts here.</h3><p>Bring your friends into the daily movement.</p></button></div><div className="info-strip"><ShieldCheck size={21}/><p><strong>Your group, your circle.</strong> Only members can see your group. Share the invite code with people you want to train alongside.</p></div>
 {modal&&<ModalFrame onClose={()=>setModal(null)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="group-modal-title"><button className="modal-close icon-button" aria-label="Close" onClick={()=>setModal(null)}><X size={21}/></button><span className="stat-icon orange"><Users size={26}/></span><h2 id="group-modal-title">{modal==='create'?'Start your own crew.':'Find your crew.'}</h2><p>{modal==='create'?'Give your group a name. We’ll take care of the invite code.':'Enter the invite code shared by your group owner.'}</p><form onSubmit={submit}><label>{modal==='create'?'Group name':'Invite code'}<input autoFocus required minLength={modal==='create'?2:1} maxLength={modal==='create'?50:30} value={value} onChange={e=>setValue(e.target.value)} placeholder={modal==='create'?'e.g. The Morning Crew':'Enter code'}/></label><button disabled={busy} className="button primary full-width">{busy?'One moment…':modal==='create'?'Create group':'Join group'}</button></form></section></ModalFrame>}
 {active&&<ModalFrame onClose={()=>setActive(null)}><section className="modal wide-modal" role="dialog" aria-modal="true" aria-labelledby="group-detail-title"><button className="modal-close icon-button" aria-label="Close" onClick={()=>setActive(null)}><X size={21}/></button><div className="eyebrow">YOUR GROUP · TODAY</div><h2 id="group-detail-title">{active.name}</h2><p>Only ranked repetitions completed after joining count here. {demo?'Sample standings.':''}</p><ModePicker mode={mode} onChange={setMode}/>{MODES[mode].experimental&&<p className="mode-status">Experimental practice mode. Live ranking is not enabled.</p>}<div className="invite-box"><span>Invite code <strong>{active.invite_code}</strong></span><button className="icon-button" aria-label="Copy invite code" onClick={()=>copy(active.invite_code)}><Copy size={18}/></button></div><RankingRows rows={rows}/><div className="group-management">{active.owner_id===data.profile.id?<><button disabled={busy} className="button secondary" onClick={()=>manage(active,'rotate')}><RefreshCw size={15}/>New invite code</button><button disabled={busy} className="text-button danger" onClick={()=>manage(active,'delete')}>Delete group</button>{members.filter(r=>r.user_id!==data.profile.id).map(r=><div className="member-management" key={r.user_id}><span>{r.nickname}</span><button disabled={busy} className="text-button danger" onClick={()=>manage(active,'remove',r.user_id)}>Remove member</button></div>)}</>:<button disabled={busy} className="button secondary danger" onClick={()=>manage(active,'leave')}>Leave group</button>}</div></section></ModalFrame>}
 </>;
}
export function Profile(){
 const {allData,data,demo,setData,refresh,notice}=useApp();const [nickname,setNickname]=useState(data.profile.nickname),[busy,setBusy]=useState(false),[image,setImage]=useState<File|null>(null);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{if(demo)setData(d=>({...d,profile:{...d.profile,nickname:nickname.trim()}}));else{await api('profile',{nickname});await refresh();}notice(demo?'Preview nickname updated for this visit.':'Profile updated. Looking good!');}catch(e){notice((e as Error).message);}finally{setBusy(false);}};
 const avatarSaved=async(blob:Blob)=>{setBusy(true);try{if(demo){setData(d=>({...d,profile:{...d.profile,avatar_url:URL.createObjectURL(blob)}}));notice('Photo updated in this preview.');}else{const form=new FormData();form.append('avatar',blob,'avatar.webp');const r=await fetch('/api/avatar',{method:'POST',body:form});const result=await r.json();if(!r.ok)throw new Error(result.error);await refresh();notice('Profile photo updated.');}setImage(null);}catch(e){notice((e as Error).message);}finally{setBusy(false);}};
 return <><Title eyebrow="THIS IS YOUR JOURNEY" title="Every rep tells your story." subtitle="A familiar face. Your own pace. Progress that’s yours."/><div className="profile-layout"><section className="card profile-card"><Avatar name={data.profile.nickname} src={data.profile.avatar_url} size="large"/><h2>{data.profile.nickname}</h2><span className="member-since">Athlete since {displayDate(data.profile.created_at,{month:'long',year:'numeric'})}</span><div className="mode-totals">{EXERCISE_MODES.map(m=><div key={m}><strong>{(allData.totalsByMode?.[m]??(m==='standard'?allData.total:0)).toLocaleString()}</strong><span>Lifetime {MODES[m].label.toLowerCase()} reps</span>{MODES[m].experimental&&<small>Practice total</small>}</div>)}</div><span className="profile-earned"><ShieldCheck size={15}/>Every repetition earned.</span></section><section className="card profile-form"><SectionHeading title="Make yourself at home" caption="A few details to make your profile yours."/><form onSubmit={save}><label>Nickname<input required minLength={1} maxLength={30} value={nickname} onChange={e=>setNickname(e.target.value)}/><small>This is how you appear on leaderboards and in groups.</small></label><label>Profile photo<div className="upload-zone"><ImagePlus size={25}/><div><strong>Choose a photo</strong><span>JPG, PNG or WebP · up to 10 MB</span></div><input type="file" accept="image/jpeg,image/png,image/webp" aria-label="Choose profile photo" onChange={e=>{const file=e.target.files?.[0];if(file){if(file.size>10*1024*1024)notice('Choose a photo smaller than 10 MB.');else setImage(file);}e.target.value='';}}/></div></label><div className="readonly-field"><span>Registration date</span><strong>{displayDate(data.profile.created_at,{year:'numeric'})}</strong><small>Your account’s original start date.</small></div><button disabled={busy} className="button primary">{busy?'Saving…':'Save changes'}<Check size={17}/></button></form></section></div><section className="card account-controls"><div><h3>Your account</h3><p>{demo?'This is a sample profile. Connect Supabase to create your own.':'Your email and private session details never appear on leaderboards.'}</p></div>{demo?<Link href="/login" className="button secondary">Account setup <ArrowUpRight size={15}/></Link>:<button className="button secondary" onClick={async()=>{await browserClient().auth.signOut();window.location.href='/login';}}><LogOut size={16}/>Sign out</button>}</section>{image&&<AvatarCrop file={image} busy={busy} onCancel={()=>setImage(null)} onSave={avatarSaved}/>}</>;
}
